# Generated by Django 5.2.8 on 2025-11-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('DRILL', 'Drill Practice'), ('PARADE', 'Parade'), ('CAMP', 'Camp'), ('TRAINING', 'Training'), ('COMPETITION', 'Competition'), ('SOCIAL_SERVICE', 'Social Service'), ('CULTURAL', 'Cultural Program'), ('SPORTS', 'Sports Event'), ('SEMINAR', 'Seminar/Workshop'), ('OTHER', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('registration_start_date', models.DateField(blank=True, null=True)),
                ('registration_end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('venue_details', models.TextField(blank=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('REGISTRATION_OPEN', 'Registration Open'), ('REGISTRATION_CLOSED', 'Registration Closed'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='accounts.officer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='units.unit')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.officer')),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='accounts.cadet')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'db_table': 'event_registrations',
                'ordering': ['-registration_date'],
                'unique_together': {('event', 'cadet')},
            },
        ),
    ]
