# Generated by Django 5.2.8 on 2025-11-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('achievement_type', models.CharField(choices=[('MEDAL', 'Medal'), ('TROPHY', 'Trophy'), ('AWARD', 'Award'), ('RECOGNITION', 'Recognition'), ('DISTINCTION', 'Distinction')], max_length=20)),
                ('description', models.TextField()),
                ('date_awarded', models.DateField()),
                ('awarded_by', models.CharField(max_length=200)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='achievements/')),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.cadet')),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ['-date_awarded'],
            },
        ),
    ]
