# Generated by Django 5.2.8 on 2025-11-11 04:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('achievements', '0002_initial'),
        ('events', '0002_eventannouncement_eventparticipation_eventresource_and_more'),
        ('training', '0002_alter_trainingenrollment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='citation',
            field=models.TextField(blank=True, help_text='Official citation or commendation text'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='level',
            field=models.CharField(choices=[('UNIT', 'Unit Level'), ('GROUP', 'Group Level'), ('DIRECTORATE', 'Directorate Level'), ('NATIONAL', 'National Level'), ('INTERNATIONAL', 'International Level')], default='UNIT', max_length=20),
        ),
        migrations.AddField(
            model_name='achievement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/photos/'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='position',
            field=models.IntegerField(blank=True, help_text='Position/Rank achieved (for competitions)', null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='training.training'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='verification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievement',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_achievements', to='accounts.officer'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('MEDAL', 'Medal'), ('TROPHY', 'Trophy'), ('AWARD', 'Award'), ('RECOGNITION', 'Recognition'), ('DISTINCTION', 'Distinction'), ('HONOR', 'Honor'), ('SCHOLARSHIP', 'Scholarship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='awarded_by',
            field=models.CharField(help_text='Authority who awarded this achievement', max_length=200),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='events.event'),
        ),
    ]
