# Generated by Django 5.2.8 on 2025-11-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wing', models.CharField(choices=[('ARMY', 'Army Wing'), ('NAVY', 'Navy Wing'), ('AIR', 'Air Wing')], max_length=10)),
                ('unit_code', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'units',
                'ordering': ['name'],
            },
        ),
    ]
