# Generated by Django 5.2.8 on 2025-11-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('A', 'A Certificate'), ('B', 'B Certificate'), ('C', 'C Certificate'), ('PARTICIPATION', 'Participation Certificate'), ('ACHIEVEMENT', 'Achievement Certificate'), ('MERIT', 'Merit Certificate')], max_length=20)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('issued_date', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.cadet')),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issued_date'],
            },
        ),
    ]
