# Generated by Django 5.2.8 on 2025-11-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
        ('events', '0002_eventannouncement_eventparticipation_eventresource_and_more'),
        ('training', '0002_alter_trainingenrollment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='training.training'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('A', 'A Certificate'), ('B', 'B Certificate'), ('C', 'C Certificate'), ('PARTICIPATION', 'Participation Certificate'), ('ACHIEVEMENT', 'Achievement Certificate'), ('MERIT', 'Merit Certificate'), ('TRAINING', 'Training Certificate'), ('APPRECIATION', 'Appreciation Certificate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='events.event'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
