# Generated by Django 5.2.8 on 2025-11-11 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventannouncement_eventparticipation_eventresource_and_more'),
        ('notifications', '0001_initial'),
        ('training', '0002_alter_trainingenrollment_options_and_more'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('EVENT', 'Event Notification'), ('ATTENDANCE', 'Attendance Alert'), ('CERTIFICATE', 'Certificate Update'), ('TRAINING', 'Training Notification'), ('ACHIEVEMENT', 'Achievement Update'), ('GENERAL', 'General Announcement'), ('REGISTRATION', 'Registration Status'), ('REMINDER', 'Reminder')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('target_audience', models.CharField(choices=[('ALL_CADETS', 'All Cadets'), ('ALL_OFFICERS', 'All Officers'), ('UNIT', 'Specific Unit'), ('YEAR', 'Specific Year'), ('ALL', 'Everyone')], max_length=20)),
                ('target_year', models.IntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'bulk_notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='URL to redirect when clicked', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.training'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('EVENT', 'Event Notification'), ('ATTENDANCE', 'Attendance Alert'), ('CERTIFICATE', 'Certificate Update'), ('TRAINING', 'Training Notification'), ('ACHIEVEMENT', 'Achievement Update'), ('GENERAL', 'General Announcement'), ('REGISTRATION', 'Registration Status'), ('REMINDER', 'Reminder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddField(
            model_name='bulknotification',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulknotification',
            name='target_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.unit'),
        ),
    ]
