# Generated by Django 5.2.8 on 2025-11-28 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('UNKNOWN', 'Unknown Face'), ('MULTIPLE', 'Multiple Faces Detected'), ('NONE', 'No Face Detected')], help_text='Status of the face recognition attempt', max_length=10)),
                ('confidence', models.FloatField(blank=True, help_text='Confidence score of the face match (0-1)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the device used for attendance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cadet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_attendance_logs', to='accounts.cadet')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_attendance_logs', to='attendance.attendancesession')),
            ],
            options={
                'verbose_name': 'Face Attendance Log',
                'verbose_name_plural': 'Face Attendance Logs',
                'db_table': 'face_attendance_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.BinaryField(help_text='Pickled face encoding data')),
                ('face_thumbnail', models.ImageField(help_text='Thumbnail of the registered face', upload_to='face_thumbnails/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this face encoding is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadet', models.OneToOneField(help_text='The cadet this face encoding belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to='accounts.cadet')),
            ],
            options={
                'verbose_name': 'Face Encoding',
                'verbose_name_plural': 'Face Encodings',
                'db_table': 'face_encodings',
            },
        ),
    ]
