# Generated by Django 5.2.8 on 2025-11-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('training_type', models.CharField(choices=[('WEAPON', 'Weapon Training'), ('MAP', 'Map Reading'), ('FIRST_AID', 'First Aid'), ('DRILL', 'Drill Training'), ('PHYSICAL', 'Physical Training'), ('LEADERSHIP', 'Leadership Training'), ('OTHER', 'Other')], max_length=20)),
                ('duration_hours', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_trainings', to='accounts.officer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='units.unit')),
            ],
            options={
                'db_table': 'trainings',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('completion_status', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to='accounts.cadet')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='training.training')),
            ],
            options={
                'db_table': 'training_enrollments',
                'unique_together': {('training', 'cadet')},
            },
        ),
    ]
