# Generated by Django 5.2.8 on 2025-11-10 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingenrollment',
            options={'ordering': ['-enrollment_date']},
        ),
        migrations.RenameField(
            model_name='trainingenrollment',
            old_name='score',
            new_name='overall_score',
        ),
        migrations.AddField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Any prerequisites for this training'),
        ),
        migrations.AddField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='training',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='trainings/syllabus/'),
        ),
        migrations.AddField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='training',
            name='venue_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='certificate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='practical_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='theory_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.CharField(choices=[('WEAPON', 'Weapon Training'), ('MAP', 'Map Reading'), ('FIRST_AID', 'First Aid'), ('DRILL', 'Drill Training'), ('PHYSICAL', 'Physical Training'), ('LEADERSHIP', 'Leadership Training'), ('ADVENTURE', 'Adventure Training'), ('COMMUNICATION', 'Communication Skills'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
